spring:
  r2dbc:
    pool:
      max-size: 20
      initial-size: 10
      validation-query: SELECT 1;
    url: r2dbc:postgresql://localhost:5432/access
    username: postgres
    password: admin
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
    url: jdbc:postgresql://localhost:5432/access
    user: postgres
    password: admin
  jpa:
    properties:
      hibernate:
        default_schema: public
        show_sql: true
    hibernate:
      ddl-auto: none
application:
  security:
    access-token-expiration: 600000 # 10 minutes
    refresh-token-expiration: 86400000 # 24 hours
    secret-key: 5266556A586E3404E63272357538F4428472B4B6250645367566B5970IL0VEU3000