--liquibase formated sql
--changeset nhanvtruong:202411230900
CREATE TABLE IF NOT EXISTS tbl_users
(
    user_id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         VARCHAR(255),
    last_modified_by   VARCHAR(255),
    created_date       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    username           VARCHAR(255)                            NOT NULL,
    password_hashed           VARCHAR(255)                            NOT NULL,
    email              VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_tbl_users PRIMARY KEY (user_id)
);

ALTER TABLE tbl_users ADD CONSTRAINT uc_tbl_users_email UNIQUE (email);

ALTER TABLE tbl_users ADD CONSTRAINT uc_tbl_users_username UNIQUE (username);